### PR TITLE
Added images

### PR DESCRIPTION
**Pull request by Molorkey**
Heya I just added Images for our menu! :)

### CODE REVIEW

**Comment by CheezuKimbap** [comment]
okaay notedXD

**Comment by Molorkey** [comment]
> okaay notedXD

Wish you a Happy christmas!

**Comment by Molorkey** [comment]
Hey senior I just wanna ask about how it's going?

**Comment by CheezuKimbap** [comment]
Hey junior, I just want your know that your request has been merged!

**Comment by Molorkey** [comment]
> Hey junior, I just want your know that your request has been merged!

Okay! Just let me know if we encounter any problems regarding the project :)

**Pull request merged**
